# MySQL ?? ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/hotdeal_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=hotdeal
spring.datasource.password=hotdeal1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=16379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

portone.api-secret=${PORTONE_API_SECRET}
portone.store-id=${PORTONE_STORE_ID}